### ISSUE TITLE
Deploy failure in GH Action

### ISSUE THREAD

**Issue by mfernandes61** [elixir-europe-training/ELIXIR-TrP-LessonTemplate-MkDocs#24]
@GeertvanGeest - could you help please?

Repo is [ELIXIR-TrP-LiterateProgrammingR-CodeRep](https://github.com/elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep) 

Editted chapter01.md and in GitHub actions I get the following output from the deploy part of GH actions (Note I have not altered references.md)
INFO     -  Building documentation to directory: /home/runner/work/ELIXIR-TrP-LiterateProgrammingR-CodeRep/ELIXIR-TrP-LiterateProgrammingR-CodeRep/site
[154](https://github.com/elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep/actions/runs/5336095951/jobs/9670270427#step:4:155)
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
[155](https://github.com/elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep/actions/runs/5336095951/jobs/9670270427#step:4:156)
  - course_schedule.md
[156](https://github.com/elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep/actions/runs/5336095951/jobs/9670270427#step:4:157)
  - keywords.md
[157](https://github.com/elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep/actions/runs/5336095951/jobs/9670270427#step:4:158)
ERROR    -  Error reading page 'chapters/references.md': Document is empty
[158](https://github.com/elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep/actions/runs/5336095951/jobs/9670270427#step:4:159)
Traceback (most recent call last):
[159](https://github.com/elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep/actions/runs/5336095951/jobs/9670270427#step:4:160)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/bin/mkdocs", line 8, in <module>
[160](https://github.com/elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep/actions/runs/5336095951/jobs/9670270427#step:4:161)
    sys.exit(cli())
[161](https://github.com/elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep/actions/runs/5336095951/jobs/9670270427#step:4:162)
             ^^^^^
[162](https://github.com/elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep/actions/runs/5336095951/jobs/9670270427#step:4:163)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
[163](https://github.com/elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep/actions/runs/5336095951/jobs/9670270427#step:4:164)

**Comment by GeertvanGeest** [comment]
Hi Mark! 

The error says `chapters/references.md` is empty.. The site renderer doesn't like that. To fix it, add some markdown to the file (find it at `docs/chapters/references.md`) and commit+push again. 

I suppose you followed all instructions, so this would be a 'bug' of the template that we should address.

@ac812: you didn't run into this when testing?

**Comment by mfernandes61** [comment]
Hi I added a line of markdown at top of file
'## references go here' and did pull & merge and it worked!

Note that previously I have done this on this and other repos (containers one) and they built fine with the empty references.md  so this appears to be new 'bug'

Thanks for quick response,
Mark

**Comment by GeertvanGeest** [comment]
Awesome, thanks for the feedback. 
I think the new version of mkdocs checks for actual markdown and doesn't allow 'any text' anymore. Keeping this open until fixed.

**Comment by GeertvanGeest** [comment]
Closing because of inactivity.
